### ISSUE TITLE
Invalid Discord invite link

### ISSUE THREAD

**Issue by inoue2002** [RadicalxChange/rxc-voice#101]
**Describe the bug**
Invalid Discord invites link.
**To Reproduce**
Click the invite link in README.md.
**Expected behavior**
we can join the discord server.

**Screenshots**

<img width="524" alt="image" src="https://user-images.githubusercontent.com/54356188/172031705-c8741c40-7eef-4ae3-9db2-1cf27bb5ebf2.png">

**Additional context**
I want to contribute this project more fun!

**Comment by tkgshn** [comment]
I'll contribute a new link what was generated by me.

**Comment by tkgshn** [comment]
it's work: https://discord.gg/Q2z3FWwTzJ

**Comment by alexrandaccio** [comment]
Just updated the README on the development branch. Thanks all for bringing this to my attention!
