### ISSUE TITLE
Proposals swapping order as I type in new proposal

### ISSUE THREAD

**Issue by whatSocks** [RadicalxChange/rxc-voice#90]
**Describe the bug**
As I enter new proposals, my current proposals swap order

**To Reproduce**
create an event
start adding proposals to the ballot
view the existing ballot items changing

**Expected behavior**
create an event
start adding proposals to the ballot
view the existing ballot items NOT changing

**Screenshots**
<img width="755" alt="Screen Shot 2022-01-21 at 8 36 37 PM" src="https://user-images.githubusercontent.com/2731744/150619632-0e7f123a-c8e3-4a86-a9c8-7b9d90f0bc6a.png">

Firefox on Mac

**Comment by alexrandaccio** [comment]
This is a good one for first-time contributors to try! I'll provide steps to solve this below.

**Comment by alexrandaccio** [comment]
Reformatted this to "first timers only" style in issue #94 

Thank you @whatSocks ! 🚀
